name: gouliard
favicon: null
layout_spectrum: 0.3049686935264617
typography_spectrum: 0.8021727001760155
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3125
  lightness: 0.6723914197646081
  saturation: 0.41035693348385394
  rhythmicContrast: 1
purpose: []
